# Multiple Linear Regression

## Importing the libraries

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [15]:
dataset=pd.read_csv('50_Startups.csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

## Encoding categorical data

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
#Here we are fitting as well as transforming the X in Ct and it return matrix of features
#with one hot encoding of categorical column state and we have to supply this an input
#for future machinery models we have to convert this into numpy array
X=np.array(ct.fit_transform(X))

## Splitting the dataset into the Training set and Test set

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Training the Multiple Linear Regression model on the Training set

In [18]:
from sklearn.linear_model import LinearRegression
#1.We dont have to be worry about dummy trap the class will take care of that
#2.We dont have to worry about selecting the best features which has higher p value
#or which is highly statistically significant for prediction of output
#as class will take care of that also
#Now here we are making regressor which is the object of LinearRegressor Class and
#it is only the multiple regression model
regressor=LinearRegression()
#to train on the training set
regressor.fit(X_train,y_train)

LinearRegression()

## Predicting the Test set results

In [19]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)
#Any numerical values will have only two digits after the comma so that
#it will be easy to visualize and also beautiful to visualize


In [20]:
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_pred),1)),1)

array([[103015.2 , 103282.38],
       [132582.28, 144259.4 ],
       [132447.74, 146121.95],
       [ 71976.1 ,  77798.83],
       [178537.48, 191050.39],
       [116161.24, 105008.31],
       [ 67851.69,  81229.06],
       [ 98791.73,  97483.56],
       [113969.44, 110352.25],
       [167921.07, 166187.94]])

In [21]:
#Concatnate the vector of predicted profits and vector of real profits and reshaping it
#in vertical form to visualize for that first is length of row in the column and second
#argument we want 1 column


print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_pred),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [22]:
print(y_pred.reshape(len(y_pred),1))

[[103015.2 ]
 [132582.28]
 [132447.74]
 [ 71976.1 ]
 [178537.48]
 [116161.24]
 [ 67851.69]
 [ 98791.73]
 [113969.44]
 [167921.07]]


In [23]:
print(y_test.reshape(len(y_pred),1))

[[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]]


In [24]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_pred),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
